### ISSUE TITLE
Change config.js according to ENV variables

### ISSUE THREAD

**Issue by PymZoR** [buckless/client#29]
It would be cool to expose SERVER_IP and SERVER_PORT, and update config.js accordingly before running the static server.

**Comment by gjuchault** [comment]
In webpack you can use https://webpack.github.io/docs/list-of-plugins.html#defineplugin which allows to create global variables but will not overrides the file `config.js`.

We could also create a webserver ourself and use webpack-dev-server in it

**Comment by gjuchault** [comment]
Fixed by #33

**Comment by gjuchault** [comment]
Closed because of Electron build
